name: Zenodo Release

on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: download archive to runner
      env:
        zipball: ${{ github.event.release.zipball_url }}
      run: |
        name=$(basename ${zipball})        
        curl -L $zipball > $name
        echo "archive=${name}" >> $GITHUB_ENV

    - name: Run Zenodo Deploy
      uses: nmfs-opensci/zenodo-release@main
      with:
        token: ${{ secrets.ZENODO_TOKEN }}
        version: ${{ github.event.release.tag_name }}
        zenodo_json: .zenodo.json   # optional if adding to an existing record in Zenodo
        archive: ${{ env.archive }}
        doi: '10.5281/zenodo.18557656'

        # Very first release will create the Zenodo entry. Comment out the doi: line
        # After first release is successful, go to Zenodo and find the 'all releases' Doi
        #   it is on the right under the single release DOI.continue-on-error: 
        #   Copy that and up into doi: line . Like so
        #   doi: '10.5281/zenodo.6326822'
        # Without the doi: line, a new Zenodo entry will be produced for each release
